git-review-rebase: use fork method when starting multiprocessing manager.
Yann ran into an issue where the python 3.14 multiprocessing Manager seems
to refuse to start with a rather cryptic:

 ValueError: bad value(s) in fds_to_keep

Claude thinks this is because on python-3.14 the default method for manager
is "forkserver", which doesn't work in the context of an asyncio.thread.  A
potential fix is to explicitly request the use of the "fork" method.

Reported-by: Yann Sionneau <yann.sionneau@vates.tech>
Signed-off-by: Quentin Casasnovas <quentin.casasnovas@vates.tech>